version: 2

sources:
  - name: raw
    schema: gwz_raw_data
    description: Raw Data GW
    tables:
      - name: sales 
        identifier: raw_gz_sales
        description: source sales per date
        columns:
          - name: date_date
            description: sales per date
          - name: orders_id
            description: sales per order id
          - name: pdt_id
            description: sales per product id
            tests:
              - unique
              - not_null
          - name: revenue
            description: sales per revenue
          - name: quantity
            description: sales per quantity
      - name: product
        identifier: raw_gz_product
        description: source of product
        columns:
          - name: products_id
            description: unique number for a product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: product per purchase price
      - name: ship 
        identifier: raw_gz_ship 
        description: shipping per ship_cost
        columns:
          - name: orders_id
            description: shipping per orders id
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping per shipping fee
          - name: logcost
            description: greenweez raw data source of shipping per logcost
          - name: ship_cost
            description: greenweez raw data source of shipping per ship_cost